spring:
  application:
    name: notification

  datasource:
    url: jdbc:postgresql://template-db:5432/template_db
    username: template
    password: template123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  sql:
    init:
      mode: never

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: true
    url: jdbc:postgresql://template-db:5432/template_db
    user: template
    password: template123

  cloud:
    aws:
      region:
        static: us-east-1
      credentials:
        access-key: test
        secret-key: test
      sqs:
        queue-name: appointment-notification-queue
        endpoint: http://localhost:4566

server:
  port: 8084