version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
      - REGION=ap-south-2
      - ECR_URL=$ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com
      - aws ecr get-login-password --region $REGION | docker login --username AWS --password-stdin $ECR_URL

  build:
    commands:
      - echo Build started

      # Patient Service
      - docker build -t healthcare/patient-service ./patient-service
      - docker tag healthcare/patient-service:latest $ECR_URL/healthcare/patient-service:latest

      # Appointment Service
      - docker build -t healthcare/appointment-service ./appointment-service
      - docker tag healthcare/appointment-service:latest $ECR_URL/healthcare/appointment-service:latest

      # Auth Service
      - docker build -t healthcare/auth-service ./auth-service
      - docker tag healthcare/auth-service:latest $ECR_URL/healthcare/auth-service:latest

      # Notification Service
      - docker build -t healthcare/notification-service ./notification-service
      - docker tag healthcare/notification-service:latest $ECR_URL/healthcare/notification-service:latest

      # API - Gateway
      - docker build -t healthcare/api-gateway ./api-gateway
      - docker tag healthcare/api-gateway:latest $ECR_URL/healthcare/api-gateway:latest

  post_build:
    commands:
      - echo Pushing images...

      - docker push $ECR_URL/healthcare/patient-service:latest
      - docker push $ECR_URL/healthcare/appointment-service:latest
      - docker push $ECR_URL/healthcare/auth-service:latest
      - docker push $ECR_URL/healthcare/notification-service:latest
      - docker push $ECR_URL/healthcare/api-gateway:latest