CREATE TABLE template (
    id BIGSERIAL PRIMARY KEY,
    template_key VARCHAR(255) NOT NULL UNIQUE,
    body TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);