version: "3.9"

services:

  mysql-db:
    image: mysql:8
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 5s
      retries: 10
    container_name: patient_mysql
    restart: always
    environment:
      MYSQL_DATABASE: patient_db
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: patient
      MYSQL_PASSWORD: patient
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  patient-service:
    build: .
    container_name: patient_service
    depends_on:
      - mysql-db
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/patient_db
      SPRING_DATASOURCE_USERNAME: patient
      SPRING_DATASOURCE_PASSWORD: patient

volumes:
  mysql-data: