services:

  patient-db:
    image: mysql:8
    container_name: patient-db
    restart: always
    environment:
      MYSQL_DATABASE: patient_db
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: patient
      MYSQL_PASSWORD: patient
    ports:
      - "3307:3306"
    volumes:
      - patient_mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD","mysqladmin","ping","-h","localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - microservices-network


  appointment-db:
    image: mysql:8
    container_name: appointment-db
    restart: always
    environment:
      MYSQL_DATABASE: appointment_db
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: appointment
      MYSQL_PASSWORD: appointment
    ports:
      - "3308:3306"
    volumes:
      - appointment_mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD","mysqladmin","ping","-h","localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - microservices-network


  auth-db:
    image: postgres:16
    container_name: auth-db
    restart: always
    environment:
      POSTGRES_DB: auth_db
      POSTGRES_USER: auth
      POSTGRES_PASSWORD: auth
    ports:
      - "5432:5432"
    volumes:
      - auth_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL","pg_isready -U auth -d  auth_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - microservices-network


  patient-service:
    image: patient-service
    container_name: patient-service
    depends_on:
      patient-db:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://patient-db:3306/patient_db
      SPRING_DATASOURCE_USERNAME: patient
      SPRING_DATASOURCE_PASSWORD: patient
    restart: always
    networks:
      - microservices-network


  appointment-service:
    image: appointment-service
    container_name: appointment-service
    depends_on:
      appointment-db:
        condition: service_healthy
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://appointment-db:3306/appointment_db
      SPRING_DATASOURCE_USERNAME: appointment
      SPRING_DATASOURCE_PASSWORD: appointment
    restart: always
    networks:
      - microservices-network


  auth-service:
    image: auth-service
    container_name: auth-service
    depends_on:
      auth-db:
        condition: service_healthy
    ports:
      - "8082:8082"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://auth-db:5432/auth_db
      SPRING_DATASOURCE_USERNAME: auth
      SPRING_DATASOURCE_PASSWORD: auth
    restart: always
    networks:
      - microservices-network


  api-gateway:
    image: api-gateway:1.1
    container_name: api-gateway
    depends_on:
      - patient-service
      - appointment-service
      - auth-service
    ports:
      - "9090:9090"
    restart: always
    networks:
      - microservices-network


volumes:
  patient_mysql_data:
  appointment_mysql_data:
  auth_postgres_data:


networks:
  microservices-network:
    driver: bridge