version: "3.9"

services:

  mysql-appointment:
    image: mysql:8.0
    container_name: mysql-appointment
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: appointment_db
      MYSQL_USER: appointment_user
      MYSQL_PASSWORD: appointment_pass
    ports:
      - "3307:3306"
    volumes:
      - mysql_appointment_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  appointment-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: appointment-service
    depends_on:
      mysql-appointment:
        condition: service_healthy
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-appointment:3306/appointment_db
      SPRING_DATASOURCE_USERNAME: appointment_user
      SPRING_DATASOURCE_PASSWORD: appointment_pass
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    restart: always

volumes:
  mysql_appointment_data: