server:
  port: 8080

spring:
  application:
    name: patient-service
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway,metrics,prometheus

  endpoint:
    gateway:
      enabled: true
    health:
      show-details: always

  metrics:
    tags:
      application: ${spring.application.name}

  oltp:
    tracing:
      endpoint: http://tempo:4318/v1/traces

logging:
  level:
    root: INFO
    com.microservice.patient: DEBUG